package migrator

import (
	"fmt"
	"strings"
	"time"

	"github.com/rda-run/komparo/internal/config"
	"github.com/rda-run/komparo/internal/migrator/ddl"
	"github.com/rda-run/komparo/pkg/schema"
)

func GenerateFixScript(changes []SchemaChange, dbURL, sourceFile string) string {
	var parts []string

	parts = append(parts, generateHeader(dbURL, sourceFile))

	if len(changes) == 0 {
		parts = append(parts, "-- No differences found. Database already matches the snapshot.")
		return strings.Join(parts, "\n\n")
	}

	dropChanges := filterChanges(changes, ChangeDrop)
	alterChanges := filterChanges(changes, ChangeAlter)
	recreateChanges := filterChanges(changes, ChangeRecreate)
	createChanges := filterChanges(changes, ChangeCreate)

	if len(dropChanges) > 0 {
		parts = append(parts, generateDropSection(dropChanges))
	}

	if len(alterChanges) > 0 {
		parts = append(parts, generateAlterSection(alterChanges))
	}

	if len(recreateChanges) > 0 {
		parts = append(parts, generateRecreateSection(recreateChanges))
	}

	if len(createChanges) > 0 {
		parts = append(parts, generateCreateSection(createChanges))
	}

	parts = append(parts, generateFooter())

	return strings.Join(parts, "\n\n")
}

func generateHeader(dbURL, sourceFile string) string {
	redactedURL := config.RedactConnectionString(dbURL)
	timestamp := time.Now().Format("2006-01-02T15:04:05Z")

	return fmt.Sprintf(`-- Generated by Komparo fix
-- Source: %s
-- Target: %s
-- Generated at: %s
-- 
-- IMPORTANT: This is NOT a versioned migration. Review before executing.
-- This script aligns the target database with the expected schema snapshot.
-- 
-- Found %d differences to fix.`,
		sourceFile, redactedURL, timestamp, 0)
}

func generateFooter() string {
	return `-- =============================================
-- COMMIT OR ROLLBACK
-- Uncomment COMMIT to apply changes, or ROLLBACK to cancel.
-- Test first: Run with ROLLBACK; to verify, then run again with COMMIT;
-- =============================================

-- COMMIT;
-- ROLLBACK;`
}

func filterChanges(changes []SchemaChange, changeType ChangeType) []SchemaChange {
	var result []SchemaChange
	for _, c := range changes {
		if c.ChangeType == changeType {
			result = append(result, c)
		}
	}
	return result
}

func generateDropSection(changes []SchemaChange) string {
	var parts []string
	parts = append(parts, "-- =============================================")
	parts = append(parts, "-- DROP SECTION: Remove objects not in expected schema")
	parts = append(parts, "-- WARNING: These operations may delete data!")
	parts = append(parts, "-- =============================================")
	parts = append(parts, "")

	for _, c := range changes {
		sql := generateDropSQL(c)
		if sql != "" {
			parts = append(parts, sql)
		}
	}

	return strings.Join(parts, "\n")
}

func generateAlterSection(changes []SchemaChange) string {
	var parts []string
	parts = append(parts, "-- =============================================")
	parts = append(parts, "-- ALTER SECTION: Modify existing objects")
	parts = append(parts, "-- =============================================")
	parts = append(parts, "")

	for _, c := range changes {
		sql := generateAlterSQL(c)
		if sql != "" {
			parts = append(parts, sql)
		}
	}

	return strings.Join(parts, "\n")
}

func generateRecreateSection(changes []SchemaChange) string {
	var parts []string
	parts = append(parts, "-- =============================================")
	parts = append(parts, "-- RECREATE SECTION: Drop and recreate objects with different definitions")
	parts = append(parts, "-- WARNING: Check if these objects have dependencies!")
	parts = append(parts, "-- =============================================")
	parts = append(parts, "")

	for _, c := range changes {
		dropSQL := generateDropSQL(c)
		createSQL := generateCreateSQL(c)
		if dropSQL != "" && createSQL != "" {
			parts = append(parts, dropSQL)
			parts = append(parts, createSQL)
			parts = append(parts, "")
		}
	}

	return strings.Join(parts, "\n")
}

func generateCreateSection(changes []SchemaChange) string {
	var parts []string
	parts = append(parts, "-- =============================================")
	parts = append(parts, "-- CREATE SECTION: Add missing objects")
	parts = append(parts, "-- =============================================")
	parts = append(parts, "")

	for _, c := range changes {
		sql := generateCreateSQL(c)
		if sql != "" {
			parts = append(parts, sql)
		}
	}

	return strings.Join(parts, "\n")
}

func generateDropSQL(c SchemaChange) string {
	switch c.ObjectType {
	case "Table":
		if actual, ok := c.Actual.(schema.Table); ok {
			return ddl.GenerateDropTableDDL(actual.Name)
		}
	case "Column":
		if actual, ok := c.Actual.(ColumnChange); ok {
			return ddl.GenerateDropColumnDDL(actual.TableName, actual.ColumnName)
		}
	case "Index":
		if actual, ok := c.Actual.(schema.Index); ok {
			return ddl.GenerateDropIndexDDL(actual.Name)
		}
	case "Constraint":
		if actual, ok := c.Actual.(schema.Constraint); ok {
			return ddl.GenerateDropConstraintDDL(actual.TableName, actual.Name)
		}
	case "Sequence":
		if actual, ok := c.Actual.(schema.Sequence); ok {
			return ddl.GenerateDropSequenceDDL(actual.Name)
		}
	case "View":
		if actual, ok := c.Actual.(schema.View); ok {
			return ddl.GenerateDropViewDDL(actual.Name)
		}
	case "MaterializedView":
		if actual, ok := c.Actual.(schema.MatView); ok {
			return ddl.GenerateDropMatViewDDL(actual.Name)
		}
	case "Trigger":
		if actual, ok := c.Actual.(schema.Trigger); ok {
			return ddl.GenerateDropTriggerDDL(actual.TableName, actual.Name)
		}
	case "Function":
		if actual, ok := c.Actual.(schema.Function); ok {
			return ddl.GenerateDropFunctionDDL(actual.Name, actual.Args)
		}
	case "Enum":
		if actual, ok := c.Actual.(schema.Enum); ok {
			return ddl.GenerateDropEnumDDL(actual.Name)
		}
	case "Extension":
		if actual, ok := c.Actual.(schema.Extension); ok {
			return ddl.GenerateDropExtensionDDL(actual.Name)
		}
	}
	return ""
}

func generateCreateSQL(c SchemaChange) string {
	switch c.ObjectType {
	case "Table":
		if expected, ok := c.Expected.(schema.Table); ok {
			return ddl.GenerateCreateTableDDL(expected)
		}
	case "Column":
		if expected, ok := c.Expected.(ColumnChange); ok {
			return ddl.GenerateAddColumnDDL(expected.TableName, expected.Expected)
		}
	case "Index":
		if expected, ok := c.Expected.(schema.Index); ok {
			return ddl.GenerateCreateIndexDDL(expected)
		}
	case "Constraint":
		if expected, ok := c.Expected.(schema.Constraint); ok {
			return ddl.GenerateAddConstraintDDL(expected)
		}
	case "Sequence":
		if expected, ok := c.Expected.(schema.Sequence); ok {
			return ddl.GenerateCreateSequenceDDL(expected)
		}
	case "View":
		if expected, ok := c.Expected.(schema.View); ok {
			return ddl.GenerateCreateViewDDL(expected)
		}
	case "MaterializedView":
		if expected, ok := c.Expected.(schema.MatView); ok {
			return ddl.GenerateCreateMatViewDDL(expected)
		}
	case "Trigger":
		if expected, ok := c.Expected.(schema.Trigger); ok {
			return ddl.GenerateCreateTriggerDDL(expected)
		}
	case "Function":
		if expected, ok := c.Expected.(schema.Function); ok {
			return ddl.GenerateCreateOrReplaceFunctionDDL(expected)
		}
	case "Enum":
		if expected, ok := c.Expected.(schema.Enum); ok {
			return ddl.GenerateCreateEnumDDL(expected)
		}
	case "Extension":
		if expected, ok := c.Expected.(schema.Extension); ok {
			return ddl.GenerateCreateExtensionDDL(expected)
		}
	}
	return ""
}

func generateAlterSQL(c SchemaChange) string {
	switch c.ObjectType {
	case "Column":
		return generateAlterColumnSQL(c)
	case "Sequence":
		if expected, ok := c.Expected.(schema.Sequence); ok {
			return ddl.GenerateAlterSequenceDDL(expected)
		}
	case "View":
		if expected, ok := c.Expected.(schema.View); ok {
			return ddl.GenerateCreateViewDDL(expected)
		}
	case "Function":
		if expected, ok := c.Expected.(schema.Function); ok {
			return ddl.GenerateCreateOrReplaceFunctionDDL(expected)
		}
	case "Extension":
		if expected, ok := c.Expected.(schema.Extension); ok {
			return ddl.GenerateCreateExtensionDDL(expected)
		}
	}
	return ""
}

func generateAlterColumnSQL(c SchemaChange) string {
	var parts []string

	expected, expOk := c.Expected.(ColumnChange)
	_, actOk := c.Actual.(ColumnChange)

	if !expOk {
		return ""
	}

	tableName := expected.TableName
	colName := expected.ColumnName

	for _, detail := range c.Details {
		switch detail.Property {
		case "type":
			if actOk {
				parts = append(parts, fmt.Sprintf("-- ALTER COLUMN TYPE: %s -> %s", detail.OldValue, detail.NewValue))
				parts = append(parts, "-- WARNING: This may fail if data cannot be cast. Consider manual conversion.")
				parts = append(parts, ddl.GenerateAlterColumnTypeDDL(tableName, colName, expected.Expected))
			}
		case "nullable":
			nullable := expected.Expected.Nullable
			parts = append(parts, ddl.GenerateAlterColumnNullableDDL(tableName, colName, nullable))
		case "default":
			parts = append(parts, ddl.GenerateAlterColumnDefaultDDL(tableName, colName, expected.Expected.Default))
		}
	}

	return strings.Join(parts, "\n")
}
